logsBucket: 'gs://laravel-log/'

steps:
  #stage 1: Building
  - name: 'docker/compose:1.28.2'
    args: ['up', '-d']

  #Stage 2: Pushing to artifact
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/test-case-2-405013/travellist']

images:
  - 'gcr.io/test-case-2-405013/travellist/job_app:$COMMIT_SHA'
